server:
  port: 8083


spring:
  application:
    name: Notification-service

  datasource:
    url: ${SHIPTRACK_DB_URL}
    username: ${SHIPTRACK_DB_USERNAME}
    password: ${SHIPTRACK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: ${SHIPTRACK_EMAIL_HOST}
    port: ${SHIPTRACK_EMAIL_PORT}
    username: ${SHIPTRACK_EMAIL_USERNAME}
    password: ${SHIPTRACK_EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10