server:
  port: 8081

spring:
  datasource:
    url: ${SHIPTRACK_DB_URL}
    username: ${SHIPTRACK_DB_USERNAME}
    password: ${SHIPTRACK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  mail:
   host: ${SHIPTRACK_EMAIL_HOST}
   port: ${SHIPTRACK_EMAIL_PORT}
   username: ${SHIPTRACK_EMAIL_USERNAME}
   password: ${SHIPTRACK_EMAIL_PASSWORD}
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
jwt:
 secret: ${SHIPTRACK_JWT_SECRET}
 expiration: 86400000
 refresh-token:
   expiration: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  jackson:
#    serialization:
#      write-dates-as-timestamps: false