server:
  port: 8087

spring:
  application:
    name: delivery-reports-service

eureka:
  client:
    service-url:
      defaultZone: http://shiptrackpro-eureka:8761/eureka/
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
