export const demoUsers = {
  admin: {
    id: "u-admin",
    name: "admin",
    email: "admin@gmail.com",
    role: "admin",
    phone: "+910000101",
    company: "ShipTrack Pro",
    jobTitle: "Platform Administrator",
    location: "India",
    timezone: "India/tamilnadu",
    joinedAt: "2023-02-14T09:00:00Z",
  },
  operator: {
    id: "u-operator",
    name: "operator",
    email: "operator@gmail.com",
    role: "operator",
    phone: "+91234567",
    company: "ShipTrack Pro",
    jobTitle: "Delivery Driver",
    location: "India",
    timezone: "India/rajasthan",
    joinedAt: "2023-05-22T09:00:00Z",
  },
  business: {
    id: "u-business",
    name: "business",
    email: "business@gmaiil.com",
    role: "business",
    phone: "+91-665550188",
    company: "Northwind Trading Co.",
    jobTitle: "Head of Logistics",
    location: "India",
    timezone: "India/gujrat",
    joinedAt: "2023-08-03T09:00:00Z",
  },
  customer: {
    id: "u-customer",
    name: "Sam Rivera",
    email: "sam.rivera@gmail.com",
    role: "customer",
    phone: "+91-6465550177",
    jobTitle: "Recipient",
    location: "India",
    timezone: "India/Bengaluru",
    joinedAt: "2024-01-19T09:00:00Z",
  },
  support: {
    id: "u-support",
    name: "Support",
    email: "support@gmail.com",
    role: "support",
    phone: "+91-6125550199",
    company: "ShipTrack Pro",
    jobTitle: "Customer Support Agent",
    location: "India",
    timezone: "India/Kolkata",
    joinedAt: "2023-11-10T09:00:00Z",
  },
};
const now = Date.now();
const hoursAgo = (h) => new Date(now - h * 3600_000).toISOString();
const daysAhead = (d) => new Date(now + d * 86_400_000).toISOString();
const daysAgo = (d) => new Date(now - d * 86_400_000).toISOString();
export const shipments = [
  {
    id: "shp-001",
    trackingNumber: "STP-9F4K-8821",
    status: "in_transit",
    mode: "road",
    priority: "express",
    origin: {
      name: "Chicago Distribution Center",
      address: "2400 W Harrison St, Chicago, IL 60612",
      lat: 41.8781,
      lng: -87.6298,
    },
    destination: {
      name: "New York Fulfillment Hub",
      address: "47-00 5th St, Long Island City, NY 11101",
      lat: 40.7484,
      lng: -73.9857,
    },
    carrier: "ShipTrack Express",
    service: "Next-Day Freight",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    weightKg: 1240,
    pieces: 18,
    declaredValue: 48000,
    estimatedDelivery: daysAhead(1),
    pickupAt: hoursAgo(20),
    currentLocation: {
      lat: 41.0,
      lng: -80.0,
      name: "Cleveland, OH",
    },
    progress: 62,
    createdAt: daysAgo(1),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Shipment picked up",
        description: "Cargo collected from origin facility",
        location: "Chicago, IL",
        lat: 41.8781,
        lng: -87.6298,
        timestamp: hoursAgo(20),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "Departed Chicago DC",
        description: "Truck departed on I-80 East",
        location: "Chicago, IL",
        lat: 41.8781,
        lng: -87.6298,
        timestamp: hoursAgo(18),
        completed: true,
      },
      {
        id: "ev3",
        status: "in_transit",
        label: "In transit — Cleveland hub",
        description: "Stop for driver break and fuel",
        location: "Cleveland, OH",
        lat: 41.4993,
        lng: -81.6954,
        timestamp: hoursAgo(4),
        completed: true,
      },
      {
        id: "ev4",
        status: "in_transit",
        label: "Departed Cleveland",
        description: "Continuing eastbound on I-80",
        location: "Cleveland, OH",
        lat: 41.0,
        lng: -80.0,
        timestamp: hoursAgo(1),
        completed: true,
      },
      {
        id: "ev5",
        status: "out_for_delivery",
        label: "Arrival at destination hub",
        description: "Estimated arrival at NY Fulfillment Hub",
        location: "Long Island City, NY",
        lat: 40.7484,
        lng: -73.9857,
        timestamp: daysAhead(1),
        completed: false,
      },
    ],
  },
  {
    id: "shp-002",
    trackingNumber: "STP-2H7M-4410",
    status: "out_for_delivery",
    mode: "road",
    priority: "standard",
    origin: {
      name: "Dallas Warehouse",
      address: "3200 Industrial Blvd, Dallas, TX 75247",
      lat: 32.7767,
      lng: -96.797,
    },
    destination: {
      name: "Sam Rivera",
      address: "245 W 107th St, New York, NY 10025",
      lat: 40.796,
      lng: -73.9631,
    },
    carrier: "ShipTrack Express",
    service: "Ground Economy",
    customer: "Sam Rivera",
    customerId: "u-customer",
    weightKg: 6.4,
    pieces: 1,
    declaredValue: 340,
    estimatedDelivery: daysAhead(0),
    pickupAt: daysAgo(2),
    currentLocation: {
      lat: 40.7589,
      lng: -73.9851,
      name: "Manhattan, NY",
    },
    progress: 94,
    createdAt: daysAgo(2),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Package received",
        description: "Received at Dallas warehouse",
        location: "Dallas, TX",
        lat: 32.7767,
        lng: -96.797,
        timestamp: daysAgo(2),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "In transit",
        description: "Departed regional sort facility",
        location: "Memphis, TN",
        lat: 35.1495,
        lng: -90.049,
        timestamp: daysAgo(1),
        completed: true,
      },
      {
        id: "ev3",
        status: "out_for_delivery",
        label: "Out for delivery",
        description: "Loaded onto delivery van for final mile",
        location: "Manhattan, NY",
        lat: 40.7589,
        lng: -73.9851,
        timestamp: hoursAgo(3),
        completed: true,
      },
    ],
  },
  {
    id: "shp-003",
    trackingNumber: "STP-5C2P-7733",
    status: "delayed",
    mode: "ocean",
    priority: "standard",
    origin: {
      name: "Port of Los Angeles",
      address: "425 S Palos Verdes St, San Pedro, CA 90731",
      lat: 33.7365,
      lng: -118.2746,
    },
    destination: {
      name: "Northwind Trading Co.",
      address: "1400 4th Ave, Seattle, WA 98101",
      lat: 47.6101,
      lng: -122.3344,
    },
    carrier: "Pacific Maritime Lines",
    service: "Ocean Freight — LCL",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    weightKg: 8400,
    pieces: 120,
    declaredValue: 212000,
    estimatedDelivery: daysAhead(4),
    pickupAt: daysAgo(3),
    currentLocation: {
      lat: 36.0,
      lng: -122.0,
      name: "Pacific Ocean",
    },
    progress: 41,
    createdAt: daysAgo(4),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Container loaded",
        description: "Container loaded at Port of LA",
        location: "San Pedro, CA",
        lat: 33.7365,
        lng: -118.2746,
        timestamp: daysAgo(3),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "Vessel departed",
        description: "MV Pacific Star departed port",
        location: "Off California Coast",
        lat: 35.0,
        lng: -121.0,
        timestamp: daysAgo(2),
        completed: true,
      },
      {
        id: "ev3",
        status: "delayed",
        label: "Weather delay",
        description: "Route adjusted due to storm system off Oregon coast",
        location: "Pacific Ocean",
        lat: 36.0,
        lng: -122.0,
        timestamp: hoursAgo(10),
        completed: true,
      },
    ],
  },
  {
    id: "shp-004",
    trackingNumber: "STP-8B1X-1290",
    status: "delivered",
    mode: "air",
    priority: "critical",
    origin: {
      name: "Memphis Air Hub",
      address: "World Relief Way, Memphis, TN 38118",
      lat: 35.0424,
      lng: -89.9767,
    },
    destination: {
      name: "Northwind Trading Co.",
      address: "1400 4th Ave, Seattle, WA 98101",
      lat: 47.6101,
      lng: -122.3344,
    },
    carrier: "SkyCargo",
    service: "Priority Air Freight",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    weightKg: 320,
    pieces: 6,
    declaredValue: 96000,
    estimatedDelivery: daysAgo(1),
    actualDelivery: daysAgo(1),
    pickupAt: daysAgo(2),
    currentLocation: {
      lat: 47.6101,
      lng: -122.3344,
      name: "Seattle, WA",
    },
    progress: 100,
    createdAt: daysAgo(2),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Cargo received at air hub",
        description: "Accepted for Priority Air Freight",
        location: "Memphis, TN",
        lat: 35.0424,
        lng: -89.9767,
        timestamp: daysAgo(2),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "Flight departed",
        description: "Departed Memphis International",
        location: "Memphis, TN",
        lat: 35.0424,
        lng: -89.9767,
        timestamp: daysAgo(2),
        completed: true,
      },
      {
        id: "ev3",
        status: "out_for_delivery",
        label: "Arrived at destination",
        description: "Final delivery dispatched",
        location: "Seattle, WA",
        lat: 47.6101,
        lng: -122.3344,
        timestamp: daysAgo(1),
        completed: true,
      },
      {
        id: "ev4",
        status: "delivered",
        label: "Delivered",
        description: "Signed for by recipient",
        location: "Seattle, WA",
        lat: 47.6101,
        lng: -122.3344,
        timestamp: daysAgo(1),
        completed: true,
      },
    ],
  },
  {
    id: "shp-005",
    trackingNumber: "STP-3J6T-5567",
    status: "exception",
    mode: "road",
    priority: "express",
    origin: {
      name: "Atlanta Cross-Dock",
      address: "1800 Marietta Blvd NW, Atlanta, GA 30318",
      lat: 33.7537,
      lng: -84.414,
    },
    destination: {
      name: "Miami Distribution",
      address: "3300 NW 72nd Ave, Miami, FL 33122",
      lat: 25.7907,
      lng: -80.3189,
    },
    carrier: "ShipTrack Express",
    service: "Next-Day Freight",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    weightKg: 890,
    pieces: 24,
    declaredValue: 52000,
    estimatedDelivery: daysAhead(1),
    pickupAt: hoursAgo(30),
    currentLocation: {
      lat: 30.0,
      lng: -82.0,
      name: "Gainesville, FL",
    },
    progress: 55,
    createdAt: daysAgo(1),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Shipment picked up",
        description: "Collected from Atlanta Cross-Dock",
        location: "Atlanta, GA",
        lat: 33.7537,
        lng: -84.414,
        timestamp: hoursAgo(30),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "In transit",
        description: "Southbound on I-75",
        location: "Macon, GA",
        lat: 32.84,
        lng: -83.6324,
        timestamp: hoursAgo(18),
        completed: true,
      },
      {
        id: "ev3",
        status: "exception",
        label: "Vehicle breakdown",
        description: "Truck mechanical issue — replacement dispatched",
        location: "Gainesville, FL",
        lat: 30.0,
        lng: -82.0,
        timestamp: hoursAgo(2),
        completed: true,
      },
    ],
  },
  {
    id: "shp-006",
    trackingNumber: "STP-7Q9R-2248",
    status: "pending",
    mode: "rail",
    priority: "standard",
    origin: {
      name: "Kansas City Rail Terminal",
      address: "2200 Manchester Trafficway, Kansas City, MO 64129",
      lat: 39.0997,
      lng: -94.5786,
    },
    destination: {
      name: "Denver Distribution",
      address: "4700 Havana St, Denver, CO 80239",
      lat: 39.7392,
      lng: -104.9903,
    },
    carrier: "Continental Rail",
    service: "Intermodal Rail",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    weightKg: 15500,
    pieces: 200,
    declaredValue: 340000,
    estimatedDelivery: daysAhead(3),
    pickupAt: daysAhead(0),
    currentLocation: {
      lat: 39.0997,
      lng: -94.5786,
      name: "Kansas City, MO",
    },
    progress: 0,
    createdAt: hoursAgo(6),
    events: [
      {
        id: "ev1",
        status: "pending",
        label: "Shipment scheduled",
        description: "Awaiting pickup — rail car assigned",
        location: "Kansas City, MO",
        lat: 39.0997,
        lng: -94.5786,
        timestamp: hoursAgo(6),
        completed: true,
      },
    ],
  },
  {
    id: "shp-007",
    trackingNumber: "STP-4D8W-9931",
    status: "in_transit",
    mode: "air",
    priority: "express",
    origin: {
      name: "Newark Air Hub",
      address: "Terminal B, Newark, NJ 07114",
      lat: 40.7357,
      lng: -74.1724,
    },
    destination: {
      name: "Sam Rivera",
      address: "245 W 107th St, New York, NY 10025",
      lat: 40.796,
      lng: -73.9631,
    },
    carrier: "SkyCargo",
    service: "Express Air",
    customer: "Sam Rivera",
    customerId: "u-customer",
    weightKg: 2.1,
    pieces: 1,
    declaredValue: 180,
    estimatedDelivery: daysAhead(0),
    pickupAt: hoursAgo(8),
    currentLocation: {
      lat: 40.7357,
      lng: -74.1724,
      name: "Newark, NJ",
    },
    progress: 30,
    createdAt: hoursAgo(10),
    events: [
      {
        id: "ev1",
        status: "picked_up",
        label: "Package received",
        description: "Received at Newark Air Hub",
        location: "Newark, NJ",
        lat: 40.7357,
        lng: -74.1724,
        timestamp: hoursAgo(8),
        completed: true,
      },
      {
        id: "ev2",
        status: "in_transit",
        label: "Customs clearance",
        description: "Clearing customs at hub",
        location: "Newark, NJ",
        lat: 40.7357,
        lng: -74.1724,
        timestamp: hoursAgo(2),
        completed: true,
      },
    ],
  },
];
export const vehicles = [
  {
    id: "veh-1",
    unit: "TT-1042",
    type: "Semi-Truck",
    carrier: "ShipTrack Express",
    status: "active",
    driver: "Marcus Webb",
    lat: 41.0,
    lng: -80.0,
    speedKph: 88,
    fuelPct: 72,
    lastUpdate: hoursAgo(0),
    odometerKm: 248910,
    capacityKg: 22000,
    utilization: 86,
  },
  {
    id: "veh-2",
    unit: "DV-0331",
    type: "Delivery Van",
    carrier: "ShipTrack Express",
    status: "active",
    driver: "Elena Vargas",
    lat: 40.7589,
    lng: -73.9851,
    speedKph: 24,
    fuelPct: 58,
    lastUpdate: hoursAgo(0),
    odometerKm: 88240,
    capacityKg: 3500,
    utilization: 64,
  },
  {
    id: "veh-3",
    unit: "TT-1198",
    type: "Semi-Truck",
    carrier: "ShipTrack Express",
    status: "maintenance",
    driver: "Unassigned",
    lat: 33.7537,
    lng: -84.414,
    speedKph: 0,
    fuelPct: 12,
    lastUpdate: hoursAgo(5),
    odometerKm: 412003,
    capacityKg: 22000,
    utilization: 0,
  },
  {
    id: "veh-4",
    unit: "TT-2057",
    type: "Reefer Truck",
    carrier: "ColdChain Logistics",
    status: "active",
    driver: "Derek Osei",
    lat: 35.1495,
    lng: -90.049,
    speedKph: 96,
    fuelPct: 81,
    lastUpdate: hoursAgo(0),
    odometerKm: 167420,
    capacityKg: 19000,
    utilization: 92,
  },
  {
    id: "veh-5",
    unit: "DV-0418",
    type: "Delivery Van",
    carrier: "ShipTrack Express",
    status: "idle",
    driver: "Nadia Park",
    lat: 41.8781,
    lng: -87.6298,
    speedKph: 0,
    fuelPct: 90,
    lastUpdate: hoursAgo(1),
    odometerKm: 54200,
    capacityKg: 3500,
    utilization: 0,
  },
  {
    id: "veh-6",
    unit: "TT-2210",
    type: "Semi-Truck",
    carrier: "Continental Rail",
    status: "offline",
    driver: "Unassigned",
    lat: 39.0997,
    lng: -94.5786,
    speedKph: 0,
    fuelPct: 0,
    lastUpdate: hoursAgo(20),
    odometerKm: 301558,
    capacityKg: 22000,
    utilization: 0,
  },
];
export const drivers = [
  {
    id: "drv-1",
    name: "Marcus Webb",
    phone: "+1 (216) 555-0120",
    rating: 4.8,
    tripsCompleted: 1240,
    status: "on_duty",
    vehicleUnit: "TT-1042",
    hoursOnDuty: 6.5,
    licenseExpiry: "2027-08-15",
  },
  {
    id: "drv-2",
    name: "Elena Vargas",
    phone: "+1 (917) 555-0133",
    rating: 4.9,
    tripsCompleted: 880,
    status: "on_duty",
    vehicleUnit: "DV-0331",
    hoursOnDuty: 4.0,
    licenseExpiry: "2026-11-02",
  },
  {
    id: "drv-3",
    name: "Derek Osei",
    phone: "+1 (901) 555-0156",
    rating: 4.7,
    tripsCompleted: 1530,
    status: "on_duty",
    vehicleUnit: "TT-2057",
    hoursOnDuty: 8.0,
    licenseExpiry: "2027-03-22",
  },
  {
    id: "drv-4",
    name: "Nadia Park",
    phone: "+1 (312) 555-0178",
    rating: 4.6,
    tripsCompleted: 410,
    status: "on_break",
    vehicleUnit: "DV-0418",
    hoursOnDuty: 2.5,
    licenseExpiry: "2026-06-30",
  },
];
export const notifications = [
  {
    id: "ntf-1",
    type: "shipment",
    title: "Shipment delayed",
    message:
      "STP-5C2P-7733 experienced a vehicle breakdown near Gainesville, FL.",
    timestamp: hoursAgo(2),
    read: false,
    severity: "warning",
  },
  {
    id: "ntf-2",
    type: "shipment",
    title: "Out for delivery",
    message: "Package STP-2H7M-4410 is out for delivery in Manhattan, NY.",
    timestamp: hoursAgo(3),
    read: false,
    severity: "info",
  },
  {
    id: "ntf-3",
    type: "system",
    title: "Weekly report ready",
    message: "Your operations summary for last week is available to download.",
    timestamp: hoursAgo(8),
    read: true,
    severity: "info",
  },
  {
    id: "ntf-4",
    type: "alert",
    title: "Fuel level low",
    message: "Vehicle TT-1198 fuel at 12% — maintenance scheduled.",
    timestamp: hoursAgo(5),
    read: false,
    severity: "warning",
  },
  {
    id: "ntf-5",
    type: "shipment",
    title: "Shipment delivered",
    message: "STP-8B1X-1290 was delivered to Northwind Trading Co. in Seattle.",
    timestamp: daysAgo(1),
    read: true,
    severity: "success",
  },
  {
    id: "ntf-6",
    type: "billing",
    title: "Invoice paid",
    message:
      "Invoice INV-2041 for $12,400 has been paid by Northwind Trading Co.",
    timestamp: daysAgo(2),
    read: true,
    severity: "success",
  },
];
export const tickets = [
  {
    id: "tkt-1",
    reference: "TKT-4821",
    subject: "Where is my package STP-2H7M-4410?",
    customer: "Sam Rivera",
    customerId: "u-customer",
    status: "in_progress",
    priority: "standard",
    channel: "chat",
    assignee: "Taylor Chen",
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(1),
    messages: [
      {
        id: "m1",
        author: "Sam Rivera",
        body: "Hi, my package was supposed to arrive today. Can you confirm the status?",
        timestamp: hoursAgo(5),
      },
      {
        id: "m2",
        author: "Taylor Chen",
        body: "Hi Sam! Your package STP-2H7M-4410 is currently out for delivery in Manhattan and should arrive by end of day. I can share the live tracking link if that helps.",
        timestamp: hoursAgo(4),
      },
      {
        id: "m3",
        author: "Sam Rivera",
        body: "Yes please, that would be great. Thank you!",
        timestamp: hoursAgo(1),
      },
    ],
  },
  {
    id: "tkt-2",
    reference: "TKT-4822",
    subject: "Delay on ocean freight STP-5C2P-7733",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    status: "open",
    priority: "express",
    channel: "email",
    assignee: "Taylor Chen",
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(9),
    messages: [
      {
        id: "m1",
        author: "Priya Sharma",
        body: "Our ocean container was flagged as delayed. What is the revised ETA and what caused the delay?",
        timestamp: hoursAgo(9),
      },
    ],
  },
  {
    id: "tkt-3",
    reference: "TKT-4818",
    subject: "Request proof of delivery for STP-8B1X-1290",
    customer: "Northwind Trading Co.",
    customerId: "u-business",
    status: "resolved",
    priority: "standard",
    channel: "portal",
    assignee: "Taylor Chen",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(20),
    messages: [
      {
        id: "m1",
        author: "Priya Sharma",
        body: "Could you send over the signed proof of delivery for our recent air freight shipment?",
        timestamp: daysAgo(1),
      },
      {
        id: "m2",
        author: "Taylor Chen",
        body: "Absolutely — the signed POD is attached to the shipment details page now. Let me know if you need anything else!",
        timestamp: hoursAgo(20),
      },
    ],
  },
  {
    id: "tkt-4",
    reference: "TKT-4815",
    subject: "Change delivery address for STP-7Q9R-9931",
    customer: "Sam Rivera",
    customerId: "u-customer",
    status: "closed",
    priority: "standard",
    channel: "phone",
    assignee: "Taylor Chen",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    messages: [
      {
        id: "m1",
        author: "Sam Rivera",
        body: "I need to redirect my package to my office address instead.",
        timestamp: daysAgo(2),
      },
      {
        id: "m2",
        author: "Taylor Chen",
        body: "Done — the delivery address has been updated and the courier has been notified.",
        timestamp: daysAgo(1),
      },
    ],
  },
];
export const teamMembers = [
  {
    ...demoUsers.admin,
    status: "active",
    lastActive: hoursAgo(0),
  },
  {
    ...demoUsers.operator,
    status: "active",
    lastActive: hoursAgo(0),
  },
  {
    ...demoUsers.support,
    status: "active",
    lastActive: hoursAgo(1),
  },
  {
    id: "u-business",
    name: "Priya Sharma",
    email: "priya.sharma@northwindco.com",
    role: "business",
    phone: "+1 (206) 555-0188",
    company: "Northwind Trading Co.",
    jobTitle: "Head of Logistics",
    location: "Seattle, WA",
    timezone: "America/Los_Angeles",
    joinedAt: "2023-08-03T09:00:00Z",
    status: "active",
    lastActive: hoursAgo(2),
  },
  {
    id: "tm-5",
    name: "Casey Brooks",
    email: "casey.brooks@shiptrack.io",
    role: "operator",
    phone: "+1 (408) 555-0201",
    company: "ShipTrack Pro",
    jobTitle: "Logistics Operator",
    location: "San Jose, CA",
    timezone: "America/Los_Angeles",
    joinedAt: "2024-03-01T09:00:00Z",
    status: "invited",
    lastActive: "—",
  },
  {
    id: "tm-6",
    name: "Riley Foster",
    email: "riley.foster@shiptrack.io",
    role: "support",
    phone: "+1 (503) 555-0210",
    company: "ShipTrack Pro",
    jobTitle: "Support Agent",
    location: "Portland, OR",
    timezone: "America/Los_Angeles",
    joinedAt: "2024-05-12T09:00:00Z",
    status: "suspended",
    lastActive: daysAgo(14),
  },
];
export const invoices = [
  {
    id: "inv-1",
    number: "INV-2041",
    customer: "Northwind Trading Co.",
    amount: 12400,
    currency: "RUPEE",
    status: "paid",
    issuedAt: daysAgo(7),
    dueAt: daysAgo(0),
    shipments: 42,
  },
  {
    id: "inv-2",
    number: "INV-2042",
    customer: "Northwind Trading Co.",
    amount: 8650,
    currency: "RUPEE",
    status: "pending",
    issuedAt: daysAgo(1),
    dueAt: daysAhead(14),
    shipments: 28,
  },
  {
    id: "inv-3",
    number: "INV-2039",
    customer: "Northwind Trading Co.",
    amount: 15200,
    currency: "INR",
    status: "overdue",
    issuedAt: daysAgo(35),
    dueAt: daysAgo(5),
    shipments: 51,
  },
  {
    id: "inv-4",
    number: "INV-2040",
    customer: "Northwind Trading Co.",
    amount: 4300,
    currency: "RUPEE",
    status: "paid",
    issuedAt: daysAgo(14),
    dueAt: daysAgo(7),
    shipments: 15,
  },
];
export const analytics = {
  volumeByMonth: [
    {
      month: "Jan",
      shipments: 1240,
      delivered: 1180,
    },
    {
      month: "Feb",
      shipments: 1380,
      delivered: 1310,
    },
    {
      month: "Mar",
      shipments: 1510,
      delivered: 1440,
    },
    {
      month: "Apr",
      shipments: 1620,
      delivered: 1560,
    },
    {
      month: "May",
      shipments: 1780,
      delivered: 1720,
    },
    {
      month: "Jun",
      shipments: 1910,
      delivered: 1840,
    },
    {
      month: "Jul",
      shipments: 2050,
      delivered: 1990,
    },
  ],
  onTimeRate: [
    {
      week: "W1",
      rate: 94.2,
    },
    {
      week: "W2",
      rate: 95.1,
    },
    {
      week: "W3",
      rate: 93.8,
    },
    {
      week: "W4",
      rate: 96.4,
    },
    {
      week: "W5",
      rate: 97.1,
    },
    {
      week: "W6",
      rate: 96.8,
    },
  ],
  modeSplit: [
    {
      name: "Road",
      value: 58,
      color: "hsl(var(--chart-1))",
    },
    {
      name: "Air",
      value: 18,
      color: "hsl(var(--chart-6))",
    },
    {
      name: "Ocean",
      value: 14,
      color: "hsl(var(--chart-4))",
    },
    {
      name: "Rail",
      value: 10,
      color: "hsl(var(--chart-2))",
    },
  ],
  performance: [
    {
      metric: "On-time",
      value: 96.8,
    },
    {
      metric: "Transit",
      value: 88.4,
    },
    {
      metric: "Pickup",
      value: 98.1,
    },
    {
      metric: "Delivery",
      value: 95.3,
    },
  ],
  carrierPerformance: [
    {
      carrier: "ShipTrack Express",
      onTime: 97,
      total: 1840,
    },
    {
      carrier: "SkyCargo",
      onTime: 94,
      total: 620,
    },
    {
      carrier: "ColdChain Logistics",
      onTime: 92,
      total: 410,
    },
    {
      carrier: "Continental Rail",
      onTime: 89,
      total: 280,
    },
    {
      carrier: "Pacific Maritime",
      onTime: 86,
      total: 220,
    },
  ],
  statusDistribution: [
    {
      name: "In Transit",
      value: 1240,
      color: "hsl(var(--chart-1))",
    },
    {
      name: "Delivered",
      value: 1990,
      color: "hsl(var(--chart-2))",
    },
    {
      name: "Out for Delivery",
      value: 480,
      color: "hsl(var(--chart-6))",
    },
    {
      name: "Pending",
      value: 320,
      color: "hsl(var(--muted-foreground))",
    },
    {
      name: "Delayed",
      value: 90,
      color: "hsl(var(--chart-3))",
    },
    {
      name: "Exception",
      value: 28,
      color: "hsl(var(--chart-5))",
    },
  ],
  deliveryTrend24h: [
    {
      hour: "00:00",
      deliveries: 42,
      pickups: 18,
    },
    {
      hour: "03:00",
      deliveries: 28,
      pickups: 12,
    },
    {
      hour: "06:00",
      deliveries: 65,
      pickups: 48,
    },
    {
      hour: "09:00",
      deliveries: 142,
      pickups: 96,
    },
    {
      hour: "12:00",
      deliveries: 188,
      pickups: 74,
    },
    {
      hour: "15:00",
      deliveries: 210,
      pickups: 52,
    },
    {
      hour: "18:00",
      deliveries: 176,
      pickups: 38,
    },
    {
      hour: "21:00",
      deliveries: 98,
      pickups: 24,
    },
  ],
  businessCostTrend: [
    {
      month: "Jan",
      cost: 8400,
      shipments: 42,
    },
    {
      month: "Feb",
      cost: 9100,
      shipments: 48,
    },
    {
      month: "Mar",
      cost: 10200,
      shipments: 55,
    },
    {
      month: "Apr",
      cost: 9800,
      shipments: 51,
    },
    {
      month: "May",
      cost: 11200,
      shipments: 62,
    },
    {
      month: "Jun",
      cost: 12400,
      shipments: 68,
    },
    {
      month: "Jul",
      cost: 13100,
      shipments: 73,
    },
  ],
  businessDeliveryTime: [
    {
      month: "Jan",
      avgDays: 3.2,
    },
    {
      month: "Feb",
      avgDays: 3.0,
    },
    {
      month: "Mar",
      avgDays: 2.8,
    },
    {
      month: "Apr",
      avgDays: 2.9,
    },
    {
      month: "May",
      avgDays: 2.6,
    },
    {
      month: "Jun",
      avgDays: 2.4,
    },
    {
      month: "Jul",
      avgDays: 2.3,
    },
  ],
  businessPerformance: [
    {
      metric: "On-time",
      value: 96.8,
    },
    {
      metric: "Delivered",
      value: 94.2,
    },
    {
      metric: "Pickup",
      value: 98.1,
    },
    {
      metric: "Documentation",
      value: 99.5,
    },
  ],
};
export const activityFeed = [
  {
    id: "a1",
    actor: "Jordan Lee",
    action: "dispatched shipment",
    target: "STP-9F4K-8821",
    time: hoursAgo(1),
    type: "shipment",
  },
  {
    id: "a2",
    actor: "System",
    action: "flagged exception on",
    target: "STP-5C2P-5567",
    time: hoursAgo(2),
    type: "alert",
  },
  {
    id: "a3",
    actor: "Taylor Chen",
    action: "resolved ticket",
    target: "TKT-4818",
    time: hoursAgo(5),
    type: "support",
  },
  {
    id: "a4",
    actor: "Marcus Webb",
    action: "completed delivery for",
    target: "STP-8B1X-1290",
    time: daysAgo(1),
    type: "shipment",
  },
  {
    id: "a5",
    actor: "Priya Sharma",
    action: "paid invoice",
    target: "INV-2041",
    time: daysAgo(2),
    type: "billing",
  },
];
export const roles = [
  {
    id: "admin",
    name: "Administrator",
    description: "Manage platform, users, security, monitoring & audits",
    users: 3,
    color: "hsl(var(--chart-1))",
    permissions: [
      {
        module: "User Management",
        actions: [
          { label: "View", allowed: true },
          { label: "Create", allowed: true },
          { label: "Edit", allowed: true },
          { label: "Delete", allowed: true },
        ],
      },
      {
        module: "Role Management",
        actions: [
          { label: "View", allowed: true },
          { label: "Edit", allowed: true },
          { label: "Delete", allowed: true },
          { label: "Admin", allowed: true },
        ],
      },
      {
        module: "Shipments",
        actions: [
          { label: "View", allowed: true },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "POD Verification",
        actions: [
          { label: "View", allowed: true },
          { label: "Verify", allowed: true },
          { label: "Reject", allowed: true },
          { label: "Upload", allowed: false },
        ],
      },
      {
        module: "Audit Logs",
        actions: [
          { label: "View", allowed: true },
          { label: "Export", allowed: true },
          { label: "Filter", allowed: true },
          { label: "Admin", allowed: true },
        ],
      },
      {
        module: "System Config",
        actions: [
          { label: "View", allowed: true },
          { label: "Edit", allowed: true },
          { label: "Deploy", allowed: true },
          { label: "Admin", allowed: true },
        ],
      },
      {
        module: "Analytics",
        actions: [
          { label: "View", allowed: true },
          { label: "Export", allowed: true },
          { label: "Admin", allowed: true },
          { label: "Share", allowed: true },
        ],
      },
    ],
  },
  {
    id: "operator",
    name: "Logistics Operator",
    description: "Delivery personnel responsible for shipment execution",
    users: 12,
    color: "hsl(var(--chart-2))",
    permissions: [
      {
        module: "Shipments",
        actions: [
          { label: "View (assigned)", allowed: true },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "Shipment Status",
        actions: [
          { label: "Update", allowed: true },
          { label: "Pick Up", allowed: true },
          { label: "In Transit", allowed: true },
          { label: "Deliver", allowed: true },
        ],
      },
      {
        module: "POD Submission",
        actions: [
          { label: "Upload", allowed: true },
          { label: "Capture Signature", allowed: true },
          { label: "Verify", allowed: false },
          { label: "Reject", allowed: false },
        ],
      },
      {
        module: "Location",
        actions: [
          { label: "Update", allowed: true },
          { label: "View", allowed: true },
          { label: "Admin", allowed: false },
          { label: "Export", allowed: false },
        ],
      },
      {
        module: "User Management",
        actions: [
          { label: "View", allowed: false },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "Analytics",
        actions: [
          { label: "View", allowed: false },
          { label: "Export", allowed: false },
          { label: "Admin", allowed: false },
          { label: "Share", allowed: false },
        ],
      },
    ],
  },
  {
    id: "business",
    name: "Business Client",
    description: "Company client that sends goods through the platform",
    users: 48,
    color: "hsl(var(--chart-4))",
    permissions: [
      {
        module: "Shipments",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Create", allowed: true },
          { label: "Edit (pre-pickup)", allowed: true },
          { label: "Cancel (pre-pickup)", allowed: true },
        ],
      },
      {
        module: "Tracking",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Notifications", allowed: true },
          { label: "History", allowed: true },
          { label: "Admin", allowed: false },
        ],
      },
      {
        module: "POD Records",
        actions: [
          { label: "View", allowed: true },
          { label: "Verify", allowed: false },
          { label: "Upload", allowed: false },
          { label: "Reject", allowed: false },
        ],
      },
      {
        module: "Analytics",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Export", allowed: true },
          { label: "Share", allowed: false },
          { label: "Admin", allowed: false },
        ],
      },
      {
        module: "Reports",
        actions: [
          { label: "View", allowed: true },
          { label: "Export", allowed: true },
          { label: "Admin", allowed: false },
          { label: "Share", allowed: false },
        ],
      },
      {
        module: "User Management",
        actions: [
          { label: "View", allowed: false },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
    ],
  },
  {
    id: "customer",
    name: "Customer",
    description: "Track packages & get real-time delivery updates",
    users: 1860,
    color: "hsl(var(--chart-3))",
    permissions: [
      {
        module: "Tracking",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Notifications", allowed: true },
          { label: "History", allowed: true },
          { label: "Admin", allowed: false },
        ],
      },
      {
        module: "Support",
        actions: [
          { label: "Create ticket", allowed: true },
          { label: "View (own)", allowed: true },
          { label: "Reply", allowed: true },
          { label: "Close", allowed: true },
        ],
      },
      {
        module: "Shipments",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "POD Records",
        actions: [
          { label: "View (own)", allowed: true },
          { label: "Verify", allowed: false },
          { label: "Upload", allowed: false },
          { label: "Admin", allowed: false },
        ],
      },
    ],
  },
  {
    id: "support",
    name: "Support Agent",
    description: "Assist customers and investigate shipment issues",
    users: 8,
    color: "hsl(var(--chart-6))",
    permissions: [
      {
        module: "Tickets",
        actions: [
          { label: "View", allowed: true },
          { label: "Reply", allowed: true },
          { label: "Assign", allowed: true },
          { label: "Close", allowed: true },
        ],
      },
      {
        module: "Shipments",
        actions: [
          { label: "View", allowed: true },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "POD Records",
        actions: [
          { label: "View", allowed: true },
          { label: "Verify", allowed: false },
          { label: "Upload", allowed: false },
          { label: "Reject", allowed: false },
        ],
      },
      {
        module: "Customer info",
        actions: [
          { label: "View", allowed: true },
          { label: "Edit contact", allowed: false },
          { label: "Refund", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "Notifications",
        actions: [
          { label: "View", allowed: true },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "User Management",
        actions: [
          { label: "View", allowed: false },
          { label: "Create", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Delete", allowed: false },
        ],
      },
      {
        module: "System Settings",
        actions: [
          { label: "View", allowed: false },
          { label: "Edit", allowed: false },
          { label: "Deploy", allowed: false },
          { label: "Admin", allowed: false },
        ],
      },
    ],
  },
];
export const microservices = [
  {
    id: "ms-auth",
    name: "Auth Service",
    status: "operational",
    latencyMs: 42,
    uptimePct: 99.99,
    requestsPerMin: 1240,
    errorRatePct: 0.01,
    cpuPct: 34,
    memoryPct: 58,
    version: "v2.4.1",
    lastDeploy: hoursAgo(28),
    description: "Authentication & session management",
  },
  {
    id: "ms-tracking",
    name: "Tracking Engine",
    status: "operational",
    latencyMs: 88,
    uptimePct: 99.97,
    requestsPerMin: 8420,
    errorRatePct: 0.03,
    cpuPct: 67,
    memoryPct: 72,
    version: "v3.1.0",
    lastDeploy: hoursAgo(12),
    description: "Real-time GPS & event ingestion",
  },
  {
    id: "ms-eta",
    name: "ETA Prediction API",
    status: "operational",
    latencyMs: 156,
    uptimePct: 99.95,
    requestsPerMin: 3120,
    errorRatePct: 0.08,
    cpuPct: 81,
    memoryPct: 64,
    version: "v1.8.2",
    lastDeploy: hoursAgo(4),
    description: "ML-powered delivery time prediction",
  },
  {
    id: "ms-routing",
    name: "Route Optimization",
    status: "degraded",
    latencyMs: 340,
    uptimePct: 99.82,
    requestsPerMin: 980,
    errorRatePct: 1.2,
    cpuPct: 92,
    memoryPct: 88,
    version: "v2.0.4",
    lastDeploy: daysAgo(2),
    description: "Multi-stop route planning & optimization",
  },
  {
    id: "ms-notify",
    name: "Notification Gateway",
    status: "operational",
    latencyMs: 64,
    uptimePct: 99.98,
    requestsPerMin: 5600,
    errorRatePct: 0.02,
    cpuPct: 45,
    memoryPct: 51,
    version: "v1.5.3",
    lastDeploy: daysAgo(5),
    description: "Email, SMS & push notification delivery",
  },
  {
    id: "ms-payments",
    name: "Payments Service",
    status: "operational",
    latencyMs: 210,
    uptimePct: 99.96,
    requestsPerMin: 420,
    errorRatePct: 0.05,
    cpuPct: 38,
    memoryPct: 44,
    version: "v2.2.0",
    lastDeploy: daysAgo(8),
    description: "Invoice processing & payment gateway",
  },
  {
    id: "ms-maps",
    name: "Map Tile Server",
    status: "operational",
    latencyMs: 52,
    uptimePct: 99.99,
    requestsPerMin: 12400,
    errorRatePct: 0.01,
    cpuPct: 56,
    memoryPct: 49,
    version: "v4.0.1",
    lastDeploy: daysAgo(1),
    description: "Geospatial tile rendering & caching",
  },
  {
    id: "ms-pod",
    name: "POD Storage",
    status: "maintenance",
    latencyMs: 0,
    uptimePct: 99.9,
    requestsPerMin: 0,
    errorRatePct: 0,
    cpuPct: 12,
    memoryPct: 30,
    version: "v1.3.0",
    lastDeploy: hoursAgo(2),
    description: "Proof-of-delivery document archive",
  },
];
export const auditLogs = [
  {
    id: "log-1",
    actor: "Alex Morgan",
    actorRole: "admin",
    action: "Logged in",
    category: "auth",
    target: "Dashboard",
    ipAddress: "10.0.1.24",
    timestamp: hoursAgo(0),
    severity: "info",
  },
  {
    id: "log-2",
    actor: "Alex Morgan",
    actorRole: "admin",
    action: "Updated role permissions for",
    category: "config",
    target: "Operator",
    ipAddress: "10.0.1.24",
    timestamp: hoursAgo(1),
    severity: "warning",
  },
  {
    id: "log-3",
    actor: "Jordan Lee",
    actorRole: "operator",
    action: "Dispatched shipment",
    category: "shipment",
    target: "STP-9F4K-8821",
    ipAddress: "10.0.2.51",
    timestamp: hoursAgo(2),
    severity: "info",
  },
  {
    id: "log-4",
    actor: "System",
    actorRole: "admin",
    action: "Auto-scaled Tracking Engine to 6 instances",
    category: "system",
    target: "ms-tracking",
    ipAddress: "127.0.0.1",
    timestamp: hoursAgo(3),
    severity: "info",
  },
  {
    id: "log-5",
    actor: "Taylor Chen",
    actorRole: "support",
    action: "Resolved ticket",
    category: "shipment",
    target: "TKT-4818",
    ipAddress: "10.0.3.18",
    timestamp: hoursAgo(5),
    severity: "info",
  },
  {
    id: "log-6",
    actor: "Alex Morgan",
    actorRole: "admin",
    action: "Deployed ETA Prediction API v1.8.2",
    category: "system",
    target: "ms-eta",
    ipAddress: "10.0.1.24",
    timestamp: hoursAgo(6),
    severity: "info",
  },
  {
    id: "log-7",
    actor: "Priya Sharma",
    actorRole: "business",
    action: "Paid invoice",
    category: "billing",
    target: "INV-2041",
    ipAddress: "203.0.113.42",
    timestamp: daysAgo(1),
    severity: "info",
  },
  {
    id: "log-8",
    actor: "System",
    actorRole: "admin",
    action: "Route Optimization degraded — high latency detected",
    category: "system",
    target: "ms-routing",
    ipAddress: "127.0.0.1",
    timestamp: hoursAgo(8),
    severity: "critical",
  },
  {
    id: "log-9",
    actor: "Casey Brooks",
    actorRole: "operator",
    action: "Failed login attempt",
    category: "auth",
    target: "Auth Service",
    ipAddress: "10.0.2.88",
    timestamp: hoursAgo(10),
    severity: "warning",
  },
  {
    id: "log-10",
    actor: "Alex Morgan",
    actorRole: "admin",
    action: "Suspended user",
    category: "user",
    target: "Riley Foster",
    ipAddress: "10.0.1.24",
    timestamp: daysAgo(1),
    severity: "warning",
  },
  {
    id: "log-11",
    actor: "System",
    actorRole: "admin",
    action: "Database backup completed",
    category: "system",
    target: "postgres-primary",
    ipAddress: "127.0.0.1",
    timestamp: daysAgo(1),
    severity: "info",
  },
  {
    id: "log-12",
    actor: "Jordan Lee",
    actorRole: "operator",
    action: "Created route plan",
    category: "shipment",
    target: "ROUTE-4471",
    ipAddress: "10.0.2.51",
    timestamp: daysAgo(1),
    severity: "info",
  },
  {
    id: "log-13",
    actor: "Alex Morgan",
    actorRole: "admin",
    action: "Exported audit logs",
    category: "config",
    target: "audit-2026-07",
    ipAddress: "10.0.1.24",
    timestamp: daysAgo(2),
    severity: "info",
  },
  {
    id: "log-14",
    actor: "Taylor Chen",
    actorRole: "support",
    action: "Updated shipment status to delivered",
    category: "shipment",
    target: "STP-8B1X-1290",
    ipAddress: "10.0.3.18",
    timestamp: daysAgo(2),
    severity: "info",
  },
  {
    id: "log-15",
    actor: "System",
    actorRole: "admin",
    action: "POD Storage entering maintenance window",
    category: "system",
    target: "ms-pod",
    ipAddress: "127.0.0.1",
    timestamp: hoursAgo(2),
    severity: "warning",
  },
];
export const etaPredictions = [
  {
    id: "eta-1",
    shipmentId: "shp-001",
    trackingNumber: "STP-9F4K-8821",
    origin: "Chicago, IL",
    destination: "New York, NY",
    currentProgress: 62,
    predictedEta: daysAhead(1),
    originalEta: daysAhead(1),
    confidencePct: 94,
    riskLevel: "low",
    delayMinutes: 0,
    factors: ["Clear weather", "On-schedule checkpoints", "Normal traffic"],
  },
  {
    id: "eta-2",
    shipmentId: "shp-002",
    trackingNumber: "STP-2H7M-4410",
    origin: "Dallas, TX",
    destination: "New York, NY",
    currentProgress: 94,
    predictedEta: daysAhead(0),
    originalEta: daysAhead(0),
    confidencePct: 97,
    riskLevel: "low",
    delayMinutes: 0,
    factors: ["Final mile in progress", "Recipient available"],
  },
  {
    id: "eta-3",
    shipmentId: "shp-003",
    trackingNumber: "STP-5C2P-7733",
    origin: "Los Angeles, CA",
    destination: "Seattle, WA",
    currentProgress: 41,
    predictedEta: daysAhead(5),
    originalEta: daysAhead(4),
    confidencePct: 68,
    riskLevel: "high",
    delayMinutes: 960,
    factors: [
      "Storm system off Oregon coast",
      "Vessel route adjusted",
      "Port congestion risk",
    ],
  },
  {
    id: "eta-4",
    shipmentId: "shp-005",
    trackingNumber: "STP-3J6T-5567",
    origin: "Atlanta, GA",
    destination: "Miami, FL",
    currentProgress: 55,
    predictedEta: daysAhead(2),
    originalEta: daysAhead(1),
    confidencePct: 54,
    riskLevel: "high",
    delayMinutes: 720,
    factors: [
      "Vehicle breakdown",
      "Replacement truck dispatched",
      "Driver hours-of-service limit",
    ],
  },
  {
    id: "eta-5",
    shipmentId: "shp-006",
    trackingNumber: "STP-7Q9R-2248",
    origin: "Kansas City, MO",
    destination: "Denver, CO",
    currentProgress: 0,
    predictedEta: daysAhead(3),
    originalEta: daysAhead(3),
    confidencePct: 88,
    riskLevel: "medium",
    delayMinutes: 0,
    factors: ["Awaiting pickup", "Rail car assigned", "Schedule on track"],
  },
  {
    id: "eta-6",
    shipmentId: "shp-007",
    trackingNumber: "STP-4D8W-9931",
    origin: "Newark, NJ",
    destination: "New York, NY",
    currentProgress: 30,
    predictedEta: daysAhead(0),
    originalEta: daysAhead(0),
    confidencePct: 82,
    riskLevel: "medium",
    delayMinutes: 45,
    factors: ["Customs clearance delay", "Local traffic moderate"],
  },
];
export const deliveryRoutes = [
  {
    id: "route-1",
    name: "I-80 East — Chicago to New York",
    vehicleUnit: "TT-1042",
    driver: "Marcus Webb",
    origin: {
      name: "Chicago, IL",
      lat: 41.8781,
      lng: -87.6298,
    },
    destination: {
      name: "New York, NY",
      lat: 40.7484,
      lng: -73.9857,
    },
    waypoints: [
      {
        name: "Cleveland, OH",
        lat: 41.4993,
        lng: -81.6954,
      },
      {
        name: "Pittsburgh, PA",
        lat: 40.4406,
        lng: -79.9959,
      },
    ],
    distanceKm: 1270,
    estimatedDurationHrs: 13.5,
    status: "active",
    stops: 4,
    cargoKg: 1240,
    fuelCostUsd: 480,
    optimized: true,
  },
  {
    id: "route-2",
    name: "Manhattan Final Mile",
    vehicleUnit: "DV-0331",
    driver: "Elena Vargas",
    origin: {
      name: "Long Island City, NY",
      lat: 40.7484,
      lng: -73.9857,
    },
    destination: {
      name: "Upper West Side, NY",
      lat: 40.796,
      lng: -73.9631,
    },
    waypoints: [
      {
        name: "Midtown, NY",
        lat: 40.7589,
        lng: -73.9851,
      },
    ],
    distanceKm: 18,
    estimatedDurationHrs: 2.5,
    status: "active",
    stops: 12,
    cargoKg: 340,
    fuelCostUsd: 28,
    optimized: true,
  },
  {
    id: "route-3",
    name: "Pacific Coast — LA to Seattle",
    vehicleUnit: "N/A (Vessel)",
    driver: "MV Pacific Star",
    origin: {
      name: "San Pedro, CA",
      lat: 33.7365,
      lng: -118.2746,
    },
    destination: {
      name: "Seattle, WA",
      lat: 47.6101,
      lng: -122.3344,
    },
    waypoints: [
      {
        name: "Off Oregon Coast",
        lat: 45.0,
        lng: -125.0,
      },
    ],
    distanceKm: 1740,
    estimatedDurationHrs: 72,
    status: "delayed",
    stops: 1,
    cargoKg: 8400,
    fuelCostUsd: 8200,
    optimized: false,
  },
  {
    id: "route-4",
    name: "I-75 South — Atlanta to Miami",
    vehicleUnit: "TT-1198",
    driver: "Unassigned (replacement)",
    origin: {
      name: "Atlanta, GA",
      lat: 33.7537,
      lng: -84.414,
    },
    destination: {
      name: "Miami, FL",
      lat: 25.7907,
      lng: -80.3189,
    },
    waypoints: [
      {
        name: "Gainesville, FL",
        lat: 29.6516,
        lng: -82.3248,
      },
      {
        name: "Orlando, FL",
        lat: 28.5383,
        lng: -81.3792,
      },
    ],
    distanceKm: 940,
    estimatedDurationHrs: 10,
    status: "delayed",
    stops: 3,
    cargoKg: 890,
    fuelCostUsd: 360,
    optimized: false,
  },
  {
    id: "route-5",
    name: "Intermodal Rail — KC to Denver",
    vehicleUnit: "CR-7781",
    driver: "Continental Rail",
    origin: {
      name: "Kansas City, MO",
      lat: 39.0997,
      lng: -94.5786,
    },
    destination: {
      name: "Denver, CO",
      lat: 39.7392,
      lng: -104.9903,
    },
    waypoints: [],
    distanceKm: 960,
    estimatedDurationHrs: 28,
    status: "planned",
    stops: 0,
    cargoKg: 15500,
    fuelCostUsd: 2100,
    optimized: true,
  },
];
export const podRecords = [
  {
    id: "pod-1",
    shipmentId: "shp-004",
    trackingNumber: "STP-8B1X-1290",
    recipient: "Northwind Trading Co.",
    signedBy: "Priya Sharma",
    deliveryTime: daysAgo(1),
    location: "Seattle, WA",
    status: "verified",
    notes: "Delivered to loading dock B. Signed by recipient.",
  },
  {
    id: "pod-2",
    shipmentId: "shp-002",
    trackingNumber: "STP-2H7M-4410",
    recipient: "Sam Rivera",
    signedBy: "—",
    deliveryTime: daysAhead(0),
    location: "New York, NY",
    status: "pending",
    notes: "Out for delivery — awaiting signature capture.",
  },
  {
    id: "pod-3",
    shipmentId: "shp-001",
    trackingNumber: "STP-9F4K-8821",
    recipient: "New York Fulfillment Hub",
    signedBy: "—",
    deliveryTime: daysAhead(1),
    location: "Long Island City, NY",
    status: "missing",
    notes: "In transit — POD not yet required.",
  },
  {
    id: "pod-4",
    shipmentId: "shp-003",
    trackingNumber: "STP-5C2P-7733",
    recipient: "Northwind Trading Co.",
    signedBy: "—",
    deliveryTime: daysAhead(4),
    location: "Seattle, WA",
    status: "missing",
    notes: "Ocean freight in transit — POD pending arrival.",
  },
  {
    id: "pod-5",
    shipmentId: "shp-005",
    trackingNumber: "STP-3J6T-5567",
    recipient: "Miami Distribution",
    signedBy: "—",
    deliveryTime: daysAhead(1),
    location: "Miami, FL",
    status: "missing",
    notes: "Exception in progress — POD on hold.",
  },
  {
    id: "pod-6",
    shipmentId: "shp-006",
    trackingNumber: "STP-7Q9R-2248",
    recipient: "Sam Rivera",
    signedBy: "—",
    deliveryTime: daysAhead(0),
    location: "New York, NY",
    status: "pending",
    notes: "Customs clearance in progress.",
  },
];
export const systemMetrics = [
  {
    name: "CPU Usage",
    value: 58,
    unit: "%",
    status: "ok",
    trend: "stable",
    history: [52, 54, 56, 58, 55, 58, 58],
  },
  {
    name: "Memory Usage",
    value: 64,
    unit: "%",
    status: "ok",
    trend: "up",
    history: [60, 61, 62, 63, 64, 64, 64],
  },
  {
    name: "Disk I/O",
    value: 42,
    unit: "%",
    status: "ok",
    trend: "down",
    history: [48, 46, 45, 44, 43, 42, 42],
  },
  {
    name: "Network In",
    value: 320,
    unit: "Mbps",
    status: "ok",
    trend: "up",
    history: [280, 290, 300, 310, 315, 318, 320],
  },
  {
    name: "API Error Rate",
    value: 0.04,
    unit: "%",
    status: "ok",
    trend: "down",
    history: [0.08, 0.07, 0.06, 0.05, 0.05, 0.04, 0.04],
  },
  {
    name: "Queue Depth",
    value: 142,
    unit: "msgs",
    status: "warn",
    trend: "up",
    history: [80, 95, 110, 120, 130, 138, 142],
  },
  {
    name: "DB Connections",
    value: 88,
    unit: "conn",
    status: "ok",
    trend: "stable",
    history: [85, 86, 87, 88, 88, 88, 88],
  },
  {
    name: "Cache Hit Rate",
    value: 94.2,
    unit: "%",
    status: "ok",
    trend: "up",
    history: [92, 92.5, 93, 93.5, 93.8, 94, 94.2],
  },
];
export const notificationMetrics = [
  {
    channel: "Email",
    sent: 12480,
    delivered: 12320,
    failed: 160,
    openRate: 68.4,
  },
  {
    channel: "SMS",
    sent: 8240,
    delivered: 8198,
    failed: 42,
    openRate: 96.2,
  },
  {
    channel: "Push",
    sent: 15600,
    delivered: 14920,
    failed: 680,
    openRate: 54.8,
  },
  {
    channel: "Webhook",
    sent: 3200,
    delivered: 3198,
    failed: 2,
    openRate: 100,
  },
];
export const reportTemplates = [
  {
    id: "rpt-1",
    name: "Monthly Operations Summary",
    description: "Full operations KPIs, volume, and performance breakdown",
    category: "Operations",
    format: "PDF",
    lastGenerated: daysAgo(2),
    schedule: "Monthly",
    icon: "BarChart3",
  },
  {
    id: "rpt-2",
    name: "Shipment Delivery Report",
    description: "All delivered shipments with timestamps and POD status",
    category: "Shipments",
    format: "CSV",
    lastGenerated: daysAgo(1),
    schedule: "Daily",
    icon: "Package",
  },
  {
    id: "rpt-3",
    name: "Carrier Performance Report",
    description: "On-time rate and SLA compliance per carrier",
    category: "Analytics",
    format: "PDF",
    lastGenerated: daysAgo(7),
    schedule: "Weekly",
    icon: "TrendingUp",
  },
  {
    id: "rpt-4",
    name: "Revenue & Billing Report",
    description: "Invoice summaries, payments, and outstanding balances",
    category: "Finance",
    format: "XLSX",
    lastGenerated: daysAgo(3),
    schedule: "Weekly",
    icon: "DollarSign",
  },
  {
    id: "rpt-5",
    name: "User Activity Report",
    description: "Login activity, session durations, and feature usage",
    category: "Users",
    format: "CSV",
    lastGenerated: daysAgo(1),
    schedule: "Daily",
    icon: "Users",
  },
  {
    id: "rpt-6",
    name: "Audit Trail Export",
    description: "Complete audit log with filters by actor and category",
    category: "Security",
    format: "JSON",
    lastGenerated: daysAgo(5),
    schedule: "On-demand",
    icon: "ShieldCheck",
  },
  {
    id: "rpt-7",
    name: "Fleet Utilization Report",
    description: "Vehicle usage, mileage, fuel costs, and maintenance",
    category: "Fleet",
    format: "PDF",
    lastGenerated: daysAgo(4),
    schedule: "Weekly",
    icon: "Truck",
  },
  {
    id: "rpt-8",
    name: "ETA Accuracy Report",
    description: "Prediction confidence vs actual delivery times",
    category: "Analytics",
    format: "PDF",
    lastGenerated: daysAgo(6),
    schedule: "Weekly",
    icon: "Clock",
  },
];
export const trafficIncidents = [
  {
    id: "tf-1",
    type: "accident",
    location: "I-75 North, Mile 142",
    route: "Atlanta → Miami",
    severity: "severe",
    delayMinutes: 45,
    status: "active",
    reportedAt: hoursAgo(1),
    affectedShipments: 2,
    lat: 30.27,
    lng: -81.39,
  },
  {
    id: "tf-2",
    type: "congestion",
    location: "I-80 East, Exit 16",
    route: "Chicago → New York",
    severity: "moderate",
    delayMinutes: 18,
    status: "active",
    reportedAt: hoursAgo(0),
    affectedShipments: 1,
    lat: 41.47,
    lng: -81.69,
  },
  {
    id: "tf-3",
    type: "weather",
    location: "Off Oregon Coast, Pacific Route",
    route: "LA → Seattle",
    severity: "severe",
    delayMinutes: 960,
    status: "active",
    reportedAt: hoursAgo(12),
    affectedShipments: 1,
    lat: 45.0,
    lng: -125.0,
  },
  {
    id: "tf-4",
    type: "construction",
    location: "I-95 South, Mile 78",
    route: "Newark → Manhattan",
    severity: "minor",
    delayMinutes: 12,
    status: "active",
    reportedAt: hoursAgo(3),
    affectedShipments: 1,
    lat: 40.72,
    lng: -74.07,
  },
  {
    id: "tf-5",
    type: "congestion",
    location: "I-40 West, Nashville",
    route: "Multiple routes",
    severity: "moderate",
    delayMinutes: 25,
    status: "active",
    reportedAt: hoursAgo(2),
    affectedShipments: 0,
    lat: 36.16,
    lng: -86.78,
  },
];
export const driverPerformance = [
  {
    id: "drv-1",
    name: "Marcus Webb",
    vehicleUnit: "TT-1042",
    status: "on_duty",
    rating: 4.8,
    onTimeRate: 96,
    deliveriesToday: 3,
    avgDeliveryTime: 4.2,
    hoursOnDuty: 6.5,
    fuelEfficiency: 7.2,
    incidents: 0,
  },
  {
    id: "drv-2",
    name: "Elena Vargas",
    vehicleUnit: "DV-0331",
    status: "on_duty",
    rating: 4.9,
    onTimeRate: 98,
    deliveriesToday: 12,
    avgDeliveryTime: 0.4,
    hoursOnDuty: 4.0,
    fuelEfficiency: 11.5,
    incidents: 0,
  },
  {
    id: "drv-3",
    name: "Derek Osei",
    vehicleUnit: "TT-2057",
    status: "on_duty",
    rating: 4.7,
    onTimeRate: 92,
    deliveriesToday: 2,
    avgDeliveryTime: 5.1,
    hoursOnDuty: 8.0,
    fuelEfficiency: 6.8,
    incidents: 0,
  },
  {
    id: "drv-4",
    name: "Nadia Park",
    vehicleUnit: "DV-0418",
    status: "on_break",
    rating: 4.6,
    onTimeRate: 94,
    deliveriesToday: 5,
    avgDeliveryTime: 0.8,
    hoursOnDuty: 2.5,
    fuelEfficiency: 10.2,
    incidents: 0,
  },
];
